version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  communication:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    
    deploy:
      replicas: 3
    ports:
      - "8000"
    restart: always
